# use ยง for coloring
# %pre% - prefix
# %name% - name
# %suf% - suffix
# %msg% - message
chat:
  enable: false
  reformat: false
  format: '<%pre%%name%%suf%> %msg%'

playerlist:
  reformat: true
  format: '%pre%%name%%suf%'

greylist:
  group: graylist
  track: graylist

