name: PortChuu
main: sh.chuu.port.mc.portchuu.PortChuu
version: @version@
description: Port Chuu Minecraft Server Plugin
api-version: 1.16
author: chuu_shi
website: https://port.chuu.sh
softdepend: [LuckPerms, ProtocolLib, DiscordSRV]

commands:
  portchuu:
    description: Port Chuu informational command
    usage: /portchuu
  firstseen:
    description: Get the first login of a player
    usage: /firstseen <player>
    permission: portchuu.command.firstseen
  gamemode:
    aliases: [gm]
    description: /gamemode, but only for survival and spectator modes
    usage: /gamemode <survival|spectator>
    permission: portchuu.command.gamemode
  greylist:
    aliases: [apply]
    description: Check the graylist status
    usage: /greylist [player]
    permission: portchuu.command.graylist
  info:
    aliases: [rules, links, map]
    description: Shows the server info as a book
    usage: /info
    permission: portchuu.command.info
  kill:
    usage: /kill
    description: /kill, but only self
    permission: portchuu.command.kill
  ping:
    description: Get the ping of a player
    usage: /ping [player]
    permission: portchuu.command.ping
  report:
    description: Get link to the report form
    usage: /report
    permission: portchuu.command.report
  seen:
    description: Get the last logout of a player
    usage: /seen <online player>
    permission: portchuu.command.seen
  teleport:
    aliases: [tp]
    description: /teleport, but with different dimensions
    usage: /teleport [entity] <entity|location>
    permission: portchuu.command.teleport
  tps:
    aliases: [ram]
    description: Outputs TPS (and RAM usage)
    usage: /tps
    permission: portchuu.command.tps

permissions:
  portchuu.reload:
    default: op

  portchuu.build:
    default: true
    description: Allows players to manipulate/build on the world
  portchuu.chat.url:
    default: true

  portchuu.command.firstseen:
    default: true

  portchuu.command.gamemode:
    default: op
  portchuu.command.gamemode.other:
    default: op
    children:
      - portchuu.command.gamemode

  portchuu.command.greylist:
    default: true
  portchuu.command.greylist.add:
    default: op
    children:
      - portchuu.command.greylist

  portchuu.command.info:
    default: true

  portchuu.command.kill:
    default: true

  portchuu.command.ping:
    default: true
  portchuu.command.ping.other:
    default: true
    children:
      - portchuu.command.ping

  portchuu.command.report:
    default: true

  portchuu.command.seen:
    default: true

  portchuu.command.teleport:
    default: op
  portchuu.command.teleport.other:
    default: op
    children:
      - portchuu.command.teleport

  portchuu.command.tps:
    default: op
  portchuu.command.tps.ram:
    description: Allows viewing RAM on /tps.  Can get costly since this runs garbage collector to get the exact RAM usage.
    default: op
    children:
      - portchuu.command.tps
